### ISSUE TITLE
Non-Functioning URL displayed to user on pgupdate

### ISSUE THREAD

**Issue by dellipse** [plexguide/PlexGuide.com#885]
When running pgupdate, the user is presented with this information:

> 📂  PG Update Interface
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Prior Versions? Visit > versions.pgblitz.com

The URL above does not resolve to anything.

(versions 8.6 > 8.7.5)

**Comment by Admin9705** [comment]
will check
