### ISSUE TITLE
website not working for 2 week.... 

### ISSUE THREAD

**Issue by dan3805** [plexguide/PlexGuide.com#902]
![Annotation 2020-04-12 195040](https://user-images.githubusercontent.com/35934387/79082753-f86e5200-7cf6-11ea-8f58-3af9b24e0da2.png)

i try connect , disconnect ..... ,,, i have nothing else to contact you....

**Comment by dan3805** [comment]
i can't check inbox , can't see nothing on the website ,

**Comment by dan3805** [comment]
yes a try another computer , and web browser

**Comment by vFlagR** [comment]
Will look in to this and get back to you :)

**Comment by dan3805** [comment]
okay thanks ! sorry my english i speak french

**Comment by dan3805** [comment]
nothing ? .. :(

**Comment by hazcod** [comment]
@dan3805  works for me?

**Comment by dan3805** [comment]
yeah sure , my new account is okay ! but i am a donor and i want my real accound to be fonctionnal .....

now it seem to be okay ! after 20-25 day !

**Comment by vFlagR** [comment]
The site was moved to a new host in the past week I believe. I can only assume this fixed whatever the issue was, sorry we ccouldn't help @dan3805 -- I did look in to it but couldn't see any issues with your account on our end.

-vFlagR
