### ISSUE TITLE
Traefik fails on redeploy because the Provider API value gets added additional times!

### ISSUE THREAD

**Issue by johnkennyuk** [plexguide/PlexGuide.com#904]
Describe the bug
Redeployment of Traefik via the PGX menu doesnt seem to skip the provider value setup causing the traefik.yml to get additional Pfillin / p.info values added which causes Traefik deployment to fail untill the tmp files are flushed manually.

To Reproduce
redeployment of traefik via the pgx menu causes this bug,

Expected behavior
from what i can tell that function should skip setting up that value if an interger = 1 but that doesnt appear to be working which means its not skipping adding the API KEY value even if its already there.

Screenshots

What is affected by this bug?
Traefik will not redeploy.

When does this occur?
via PGX traefik menu redeploy attempts
Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)

Operating System: Ubuntu [16.04/18.04]
18.04
Plexguide Version: 6.xx [Stable/Beta/Edge]
PGX
Plexguide Server Type: [Remote Dedi/Remote VPS or VM/Local Dedi/Local VPS or VM]
Local Dedi
Plexguide Edition: [Gdrive/Local Storage/GCE]
NA
Plexguide Mount System: [Move+PGDrive/Move+PlexDrive/PGBlitz/ST2]
NA
Using Traefik: [Yes/No]
Yes in this test
Domain DNS Provider:[CloudFlare/DuckDNS/Gandi/GoDaddy/NameCheap]
DuckDNS (but assume this applies to all providers chosen
Logs
If applicable provide the output from relevant logs and/or the output from the pglog command

Additional context
From what i can tell Traefik_info is modified using set values set via the menu, but as this p.info / pfillin value isnt skipped it gets added twice but it should only be added once or modified if its changed?

**Comment by Admin9705** [comment]
Thanks, will check into it
